version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ridehailing
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ridehailing-net

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - ridehailing-net

volumes:
  postgres_data:

networks:
  ridehailing-net:
    driver: bridge