server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
        - id: passenger_service_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/passenger/**

        - id: driver_service_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/driver/**