server:
  port: 8888

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth_service_route
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/auth/**

            - id: passenger_service_route
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/passenger/**
              filters:
                - AuthenticationFilter

            - id: driver_service_route
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/driver/**
              filters:
                - AuthenticationFilter
    discovery:
      enabled: false